version: "3.3"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/models:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=records
      - POSTGRES_USER=records
      - POSTGRES_PASSWORD=all
    ports:
      - 5432:5432
